### PR TITLE
some cool things i made

### PR DESCRIPTION
**Pull request by minqwq**

### CODE REVIEW

**Comment by minqwq** [comment]
😢

**Comment by Sunch233** [comment]
Approve

**Review by Sunch233 — APPROVED** [review]
黑框好丑

**Comment by minqwq** [comment]
嫌丑可以把关于emph那部分的css删掉

于 2024年8月16日 GMT+08:00下午2:22:41，Sunch ***@***.***> 写道：
>@Sunch233 approved this pull request.
>
>黑框好丑
>
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/Sunch233/sunch233.github.io/pull/2#pullrequestreview-2241985303
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
--minqwq

**Pull request merged**
